### ISSUE TITLE
Need command line python magic to support delta-push and cached-delta-push targets available in the solenopsis ant script

### ISSUE THREAD

**Issue by sfloess** [solenopsis/Solenopsis#131]
We need command line solenopsis wrapper script magic (in python) to support both:
* cached-delta-push
* delta-push

The properties are very similar to:
* cached-file-push
* file-push

Exception is with delta-pushes no files are expressed for remove or add.

Also need support for sf.dryRun property...

**Comment by pcon** [comment]
Adding #148 to handle the `sf.dryRun` property
