### ISSUE TITLE
Removal of items in the .sfdcignore file from profiles

### ISSUE THREAD

**Issue by pcon** [solenopsis/Solenopsis#143]
If you have the following in your `.sfdcignore` file

    layouts/FeedItem-Feed Item Layout.layout

and you have the following in one of your profiles

    <layoutAssignments>
        <layout>FeedItem-Feed Item Layout</layout>
    </layoutAssignments>

the deployment will fail because the Layout does not exist.  The current way to remedy this is to remove it from the profile files, but it keeps creeping back in profile files with a `pull-full-to-master` and it's apparently [not uncommon](http://salesforce.stackexchange.com/questions/54458/feeditem-feed-item-layout-preventing-profile-deployment)

**Comment by sfloess** [comment]
Code is in place but disabled by default for all pushes and pulls.  However, calling remove-ignore-refs will force a run on the master env.
