### ISSUE TITLE
Trailing whitepace in the .sfdcignore file does not get ignored

### ISSUE THREAD

**Issue by pcon** [solenopsis/Solenopsis#146]
If you have a line in the _.sfdcignore_ file and there is additional whitespace at the end it is not ignored.

We should probably trim all whitespace from the start and end of the ignore file lines

**Comment by sfloess** [comment]
I think this is a bug in how Ant deals with those files.  For example, we hand in the file as it is with no interpretation in Solenopsis.

However, I can certainly "step in" and coax Ant to do the right thing :)

**Comment by pcon** [comment]
I don't want to make it too difficult for us.  May be worth adding a utility to the commandline tools to do a config check.  One part of that config check could be to look for whitespace at the start/end of the .sfdcignore file

**Comment by sfloess** [comment]
I could have it automagically check it all thetime....its really easyto do.  I could have itfail or just fix with a big fat message :)

**Comment by sfloess** [comment]
Added a new target entitled ```clean-ignore-file``` - requires the ```-i``` command line option (meaning must supply the ```-Dsf.ignoreFile``` option to Ant).
