### ISSUE TITLE
Enable quick-deploy

### ISSUE THREAD

**Issue by pcon** [solenopsis/Solenopsis#151]
We should add a `--fast` option to Solenopsis that utilizes the `runTest` functionality and then adds the required test classes to XML file.  This could be combined with the `delta-push` for faster deployment.  (It would be nice if we can do something like `CaseAPI_*Test`, this would only be really useful if runTest supports it, otherwise we'd have to look on disk or in the pulled data and that would be more work that it's worth for version 1)

*Example XML File*
```xml
<target name="deployCode">
    <sf:deploy username="${sf.username}" password="${sf.password}" serverurl="${sf.serverurl}" deployroot="codepkg">
        <runTest>TestClass1</runTest>
        <runTest>TestClass2</runTest>
        <runTest>TestClass3</runTest>
    </sf:deploy>
</target>
```

We should have a way to automatically pull in the test classes.

*Example Trigger*
```java
/**
* This trigger is for cases
*
* @author Patrick Connelly (patrick@deadlypenguin.com)
* @testClasses CaseTrigger_Test
*/
trigger CaseTrigger on Case (...) {
    // code
}
```

*Example class*
```java
/**
* This is an API for cases
*
* @author Bob Dole (bdole@test.com)
* @testClasses CaseAPI_searchTest, CaseAPI_listTest, CaseAPI_getTest, CaseAPI_Test
*/
global with sharing class CaseAPI {
    //Code
}
```

The resultant deployment XML for these two objects would be

```xml
<target name="deployCode">
    <sf:deploy username="${sf.username}" password="${sf.password}" serverurl="${sf.serverurl}" deployroot="codepkg">
        // XML for pushing classes/CaseAPI.cls and triggers/CaseTrigger.trigger
        <runTest>CaseAPI_searchTest</runTest>
        <runTest>CaseAPI_listTest</runTest>
        <runTest>CaseAPI_getTest</runTest>
        <runTest>CaseAPI_Test</runTest>
        <runTest>CaseTrigger_Test</runTest>
    </sf:deploy>
</target>
```

**Comment by sfloess** [comment]
* sf.fastDeploy (true = use)
* likely only needed in file-push
* in files being pushed, scour triggers/classes for "@testClasses" and build the <runTest> child elements
* do NOT need to include test classes UNLESS they are modified
* should already have the <runTest> generation as part of (I think) specifying what tests to run - reuse this if sf.fastDeploy == true
