### ISSUE TITLE
Be able to define the location of the solenopsis.properties file

### ISSUE THREAD

**Issue by pcon** [solenopsis/Solenopsis#164]
Would be nice to run

`solenopsis --propfile=/home/user/someotherfile.properties` 

and then use that properties file.

This would be useful for people (like consultants) that are working with multiple environments and want to keep a separate solenopsis config stack for each environment.

**Comment by adambarreiro** [comment]
Hi there,

I'm starting to use Solenopsis and I was wondering if this new feature has been implemented, or if there is a proper way to store `solenopsis.properties` in other path different to `~/solenopsis.properties`?

Thank you very much!

**Comment by pcon** [comment]
@adambarreiro it has not been yet.  I'll raise this with @sfloess and see if we can get it in soon.  It'll be two parts.  First the backing Ant update then the python update.

**Comment by sfloess** [comment]
@adambarreiro - I will work on this first thing this weekend...  If I'm lucky I can get to it tonight...

**Comment by sfloess** [comment]
@adambarreiro - done...

@pcon - you are up...  I will comment on #165 (property = solenopsis.PROPERTIES).

**Comment by adambarreiro** [comment]
Thanks a lot!! ;)

**Comment by sfloess** [comment]
@adambarreiro - sure!  Happy to help!
