### ISSUE TITLE
Look for solenopsis.properties to override default properties file

### ISSUE THREAD

**Issue by pcon** [solenopsis/Solenopsis#165]
After Issue #164 is complete, update the solenopsis python wrapper to look for `solenopsis.properties` in the CWD prior to completing the ant command.  If the file exists, pass it's location into the ant command to override the default properties file.

The use case for this is similar to that of Issue #164 and would allow easier management of multiple sandboxes

**Comment by sfloess** [comment]
@pcon - the new property is `solenopsis.PROPERTIES`

Example:  `bsolenopsis -Dsolenopsis.PROPERTIES=/tmp/myProps.properties`

**Comment by sfloess** [comment]
@pcon - I also update the wiki for the [ant properties](https://github.com/solenopsis/Solenopsis/wiki/1.1-Properties).

**Comment by pcon** [comment]
Fixed in e46703aa53f271a5068576f4b563217f2e880de7
