### ISSUE TITLE
Add support for processing deletes *after* add/update

### ISSUE THREAD

**Issue by jeremyross** [solenopsis/Solenopsis#169]
Historically, the Metadata API performed deletes before adds/updates, which causes issues for doing things like this in one deployment: Delete Component A, modify Component B to remove dependency on Component A. 

Metadata API v33 added support for processing deletes either before or after the adds/updates. Solenopsis should support this new feature for scenarios like the one above.

**Comment by sfloess** [comment]
OK to close since we can now specify pre/post destructiveChanges.xml file name?

**Comment by jeremyross** [comment]
Yep.

**Comment by sfloess** [comment]
Thanks!
