### ISSUE TITLE
Solenopsis should not attempt to delete Workflow

### ISSUE THREAD

**Issue by jeremyross** [solenopsis/Solenopsis#170]
Typical error message: “Error: Cannot delete a workflow object; Workflow Rules and Actions must be deleted individually"

Workflow are deleted implicitly when an object is deleted. If an object exists, so will its workflow, even if the workflow definition is empty.

Perhaps add a list of delete exclusions to the properties file?

**Comment by sfloess** [comment]
We do support an sfdc ignore file - is that sufficient?

**Comment by jeremyross** [comment]
Yeah, that's what I've been doing.

**Comment by sfloess** [comment]
Great!  Closing now.  Let's see how this plays out in the java rewrite.
