### ISSUE TITLE
Add a flag to solenopsis to dump the build.properties and build.xml to disk

### ISSUE THREAD

**Issue by pcon** [solenopsis/Solenopsis#180]
When dealing with Salesforce support, they request the `build.properties` and `build.xml` file that is used.  Since Solenopsis generates these in memory it would be useful to be able to dump these files to disk.  I would suggest putting them in the root of the deploy folder (parent folder to `folder-pull` or `push` folders)

**Comment by jayce1996** [comment]
For reasons of security it would be good if passwords were automatically obfuscated.

**Comment by dvf1976** [comment]
re: passwords obfuscated, ideally, that'd be the default (while there could be yet-another flag) that wouldn't obfuscate the passwords.

perhaps:
--dump-files
and
--dump-files --show-passwords
?

**Comment by sfloess** [comment]
Gents,

This is gonna be an interesting problem to solve if I take this literally.  The reason I say this is that the build.xml and supporting Ant files are spread out and use variables (properties in Ant) that aren't expanded.

I think what is being asked here is to generate a build.xml with the value exanded that denotes what the call to SFDC could resemble?

If so, that's a much easier problem.

**Comment by dvf1976** [comment]
@sfloess I *think* it may be even simpler than what your proposing...

Here is what we share with SFDC currently:

<project xmlns:sf="antlib:com.salesforce" basedir=".">
    <taskdef resource="com/salesforce/antlib.xml" uri="antlib:com.salesforce" description="Salesforce Migration Tool">
        <classpath>
            <fileset file="ant-salesforce.jar"/>
        </classpath>
    </taskdef>

    
    <property name="username"     value=""/>
    <property name="password"     value=""/>
    <property name="url"          value="https://test.salesforce.com"/>
    <property name="file"         value="deploy.zip"/>
    <property name="allowMissing" value="true"/>
    <property name="checkOnly"    value="true"/>

    <sf:deploy username="${username}" password="${password}" serverurl="${url}" zipFile="${file}" allowMissingFiles="${allowMissing}" checkOnly="${checkOnly}"/>
</project>

I think the commented out section with real credentials and 'redacted' password value would be what we want for
--dump-files

and to have the password *NOT* redacted for
--dump-files --show-passwords

**Comment by sfloess** [comment]
@dvf1976 - Yep - I see your point.  I got build.xml's to generate and do as you describe above.  It was easy - but we are on the same page.

**Comment by sfloess** [comment]
Gents,

If you define:
* -Dsf.dumpFiles, a build.xml file will be generated in the tmp dir
* -Dsf.showPasswords, the build.xml (if -Dsf.dumpFiles is defined) will also contain the password (password plus security token).

Please note, this build.xml can be run and executed.  For example:
```bash
$ ant -f /tmp/sfloess/solenopsis/1.1/sfloess/push/build.xml
``` 

Not suggesting you should execute the ```build.xml```.  I am, however, stating it can be run and also submitted to tech support.
