### ISSUE TITLE
Provide python command line support for Issue #180

### ISSUE THREAD

**Issue by sfloess** [solenopsis/Solenopsis#181]
Now that Issue #180 is finished, we'll need command line support in python for:
* ```-Dsf.dumpFiles```
* ```-Dsf.showPasswords```

Please note, no value has to be set for this to work in ```ant```:
```bash
bsolenopsis -Dsf.dumpFiles -Dsf.showPasswords -Dsf.files2push="classes/XMLDom.cls" file-push
```

If you do provide a value like:
```bash
bsolenopsis -Dsf.dumpFiles="true" -Dsf.showPasswords="true" -Dsf.files2push="classes/XMLDom.cls" file-push
```
This will work as well.

**Comment by pcon** [comment]
Completed in 0c8102fd94d419a3a2a138727a382e9b4d4b8ecb
