### ISSUE TITLE
Be able to apply XSLTs to xml files

### ISSUE THREAD

**Issue by pcon** [solenopsis/Solenopsis#182]
Let's take a look at a [recent issue](https://success.salesforce.com/issues_view?id=a1p300000008YdEAAU) from SFDC.  If we have the following Admin.profile stanza then the deploy can fail because not all environments have the permission set and you cannot modify it via ANT

```xml
<?xml version="1.0" encoding="UTF-8"?>
<Profile xmlns="http://soap.sforce.com/2006/04/metadata">
    <!-- Lots more data goes here -->
    <userPermissions>
        <enabled>true</enabled>
        <name>MergeTopics</name>
    </userPermissions>
    <userPermissions>
        <enabled>true</enabled>
        <name>ModerateChatter</name>
    </userPermissions>
    <userPermissions>
        <enabled>true</enabled>
        <name>ModifyAllData</name>
    </userPermissions>
</Profile>
```

I would like to be able to write and automatically apply an XSLT to transform it to

```xml
<?xml version="1.0" encoding="UTF-8"?>
<Profile xmlns="http://soap.sforce.com/2006/04/metadata">
    <!-- Lots more data goes here -->
    <userPermissions>
        <enabled>true</enabled>
        <name>MergeTopics</name>
    </userPermissions>
    <userPermissions>
        <enabled>true</enabled>
        <name>ModifyAllData</name>
    </userPermissions>
</Profile>
```

My proposed solution would be to add an XSLT directory flag that is passed in (or stored in the `solenopsis.properties` file).  Then the XSLT is applied (if it exists) and the resultant file is added to the zip

```text
- src/
    - profiles/
        - Admin.profile
- xslt/
    - src/
        - profiles/
            - Admin.profile.xslt
```

All that would need to be done is append `.xslt/src` to the end of the file name and look for it in the provided XSLT directory.  The reason it is not relative to the `xslt` folder is it allows us to create additional directories such as `includes` without muddying up other parts of the repo.

**Comment by sfloess** [comment]
As a side piece, write an XSLT for:

```xml
Profile/userPermissions[name [text() = 'ModerateChatter']]
```

**Comment by pcon** [comment]
Another example of what we would want to use this for.

A manage package creates a field called `namespace__additionalfield__c` we do not want this field to end up in our `Account.object` file because a destructive-push will fail because of it.  So we would want to write a `xslt/src/objects/Account.object.xslt` to remove the entire field entry

**Account.object**
```xml
<?xml version="1.0" encoding="UTF-8"?>
<CustomObject xmlns="http://soap.sforce.com/2006/04/metadata">
    <!-- account information -->
    <fields>
        <fullName>namespace__additionalfield__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <deprecated>false</deprecated>
        <externalId>false</externalId>
        <label>Customer Info</label>
        <referenceTo>namespace__additionalfield__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>namespace__additionalfield</relationshipName>
        <required>false</required>
        <trackFeedHistory>false</trackFeedHistory>
        <trackHistory>false</trackHistory>
        <type>Lookup</type>
    </fields>
    <!-- more account information -->
</CustomObject>
```

Since this would also end up in any profiles we'd also want to write an XSLT to remove the `fieldPermissions` element from the `Admin.profile`.

**Admin.profile**

```xml
<?xml version="1.0" encoding="UTF-8"?>
<Profile xmlns="http://soap.sforce.com/2006/04/metadata">
    <!-- profile information -->
    <fieldPermissions>
        <editable>true</editable>
        <field>Account.namespace__additionalfield__c</field>
        <readable>true</readable>
    </fieldPermissions>
    <!-- more profile information -->
</Profile>
```
