### ISSUE TITLE
dirDiff throwing runtime exception

### ISSUE THREAD

**Issue by bk-dev** [solenopsis/Solenopsis#186]
There appears to be a typo, /abels/, in the directory it's trying to hunt down.

[rh-util:dirDiff] java.security.PrivilegedActionException: org.apache.bsf.BSFException: The application script threw an exception: java.io.FileNotFoundException: /Users/BK/.solenopsis/env/DEV/abels/CustomLabels.labels (No such file or directory) BSF info: scriptdef_http://www.redhat.com/util:dirDiff at line: 0 column: columnNo

**Comment by bk-dev** [comment]
Here's a more thorough log capture:

Buildfile: /usr/share/solenopsis/ant/solenopsis.xml

info:
     [echo] 
     [echo] Solenopsis release version  [N/A]
     [echo] Solenopsis version          [1.1]
     [echo] 
     [echo] Ant version                 [Apache Ant(TM) version 1.9.5 compiled on May 31 2015]
     [echo] Java version                [1.7]
     [echo] 		

pull-full:
   [delete] Deleting directory /var/folders/1n/943l66gd5b5b3nbfw7zdsb180000gp/T/bk/solenopsis/1.1/BK/folder-pull
    [mkdir] Created dir: /var/folders/1n/943l66gd5b5b3nbfw7zdsb180000gp/T/bk/solenopsis/1.1/BK/folder-pull
     [echo] Generating package.xml
     [echo] 
     [echo] 
     [echo] 				Processing:  [BK]
     [echo] 
     [echo] 				URL:         [https://test.salesforce.com]
     [echo] 				API:         [33.0]
     [echo] 
     [echo] 				Jar:         [/usr/share/solenopsis/ant/1.1/lib/ant-salesforce.jar]
     [echo] 
     [echo] 			
   [delete] Deleting directory /Users/bk/.solenopsis/env/BK
    [mkdir] Created dir: /Users/bk/.solenopsis/env/BK
[sf:retrieve] Request for a retrieve submitted successfully.
[sf:retrieve] Request ID for the current retrieve task: 09SR0000000nMVdMAM
[sf:retrieve] Waiting for server to finish processing the request...
[sf:retrieve] Request Status: InProgress
[sf:retrieve] Request Status: InProgress
[sf:retrieve] Request Status: InProgress
[sf:retrieve] Request Status: InProgress
[sf:retrieve] Request Status: InProgress
[sf:retrieve] Request Status: InProgress
[sf:retrieve] Request Status: InProgress
[sf:retrieve] Request Status: InProgress
[sf:retrieve] Request Status: Succeeded
[sf:retrieve] Retrieve warnings (7):
[sf:retrieve] package.xml - Entity of type 'CustomObject' named 'ServiceContract' cannot be found
[sf:retrieve] package.xml - Entity of type 'CustomObject' named 'ContractLineItem' cannot be found
[sf:retrieve] package.xml - Entity of type 'CustomObject' named 'EntitlementContact' cannot be found
[sf:retrieve] package.xml - Entity of type 'CustomObject' named 'Entitlement' cannot be found
[sf:retrieve] package.xml - Entity type 'EntitlementTemplate' is not available in this organization
[sf:retrieve] package.xml - Entity type 'Portal' is not available in this organization
[sf:retrieve] package.xml - Can't retrieve non-customizable CustomObject named: UserLicense
[sf:retrieve] Finished request 09SR0000000nMVdMAM successfully.
   [delete] Deleting: /var/folders/1n/943l66gd5b5b3nbfw7zdsb180000gp/T/bk/solenopsis/1.1/BK/folder-pull/folder-pull.package.xml
      [zip] Building zip: /var/folders/1n/943l66gd5b5b3nbfw7zdsb180000gp/T/bk/solenopsis/1.1/BK/folder-pull/folder-pull.zip
    [unzip] Expanding: /var/folders/1n/943l66gd5b5b3nbfw7zdsb180000gp/T/bk/solenopsis/1.1/BK/folder-pull/folder-pull.zip into /Users/bk/.solenopsis/env/BK
     [echo] 
     [echo]                         Purging ignores is set to [false] - therefore it is skipped!
     [echo] 
     [echo]                         If you want it enabled, ensure the value is not [false].  This
     [echo]                         can be done by defining the environment variable sf.purgeIgnores to true
     [echo]                         or any other value.
     [echo]                     

cached-delta-push:
[rh-util:dirDiff] Jul 27, 2015 4:05:19 PM org.apache.bsf.BSFManager exec
[rh-util:dirDiff] SEVERE: Exception :
[rh-util:dirDiff] java.security.PrivilegedActionException: org.apache.bsf.BSFException: The application script threw an exception: java.io.FileNotFoundException: /Users/bk/.solenopsis/env/DEV/abels/CustomLabels.labels (No such file or directory) BSF info: scriptdef_http://www.redhat.com/util:dirDiff at line: 0 column: columnNo
[rh-util:dirDiff] 	at java.security.AccessController.doPrivileged(Native Method)
[rh-util:dirDiff] 	at org.apache.bsf.BSFManager.exec(BSFManager.java:491)
[rh-util:dirDiff] 	at org.apache.tools.ant.util.optional.ScriptRunner.executeScript(ScriptRunner.java:98)
[rh-util:dirDiff] 	at org.apache.tools.ant.taskdefs.optional.script.ScriptDef.executeScript(ScriptDef.java:349)
[rh-util:dirDiff] 	at org.apache.tools.ant.taskdefs.optional.script.ScriptDefBase.execute(ScriptDefBase.java:51)
[rh-util:dirDiff] 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
[rh-util:dirDiff] 	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
[rh-util:dirDiff] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[rh-util:dirDiff] 	at java.lang.reflect.Method.invoke(Method.java:606)
[rh-util:dirDiff] 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
[rh-util:dirDiff] 	at org.apache.tools.ant.Task.perform(Task.java:348)
[rh-util:dirDiff] 	at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:68)
[rh-util:dirDiff] 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
[rh-util:dirDiff] 	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
[rh-util:dirDiff] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[rh-util:dirDiff] 	at java.lang.reflect.Method.invoke(Method.java:606)
[rh-util:dirDiff] 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
[rh-util:dirDiff] 	at org.apache.tools.ant.Task.perform(Task.java:348)
[rh-util:dirDiff] 	at org.apache.tools.ant.taskdefs.MacroInstance.execute(MacroInstance.java:396)
[rh-util:dirDiff] 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
[rh-util:dirDiff] 	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
[rh-util:dirDiff] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[rh-util:dirDiff] 	at java.lang.reflect.Method.invoke(Method.java:606)
[rh-util:dirDiff] 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
[rh-util:dirDiff] 	at org.apache.tools.ant.Task.perform(Task.java:348)
[rh-util:dirDiff] 	at org.apache.tools.ant.Target.execute(Target.java:435)
[rh-util:dirDiff] 	at org.apache.tools.ant.Target.performTasks(Target.java:456)
[rh-util:dirDiff] 	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
[rh-util:dirDiff] 	at org.apache.tools.ant.Project.executeTarget(Project.java:1376)
[rh-util:dirDiff] 	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
[rh-util:dirDiff] 	at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
[rh-util:dirDiff] 	at org.apache.tools.ant.Main.runBuild(Main.java:853)
[rh-util:dirDiff] 	at org.apache.tools.ant.Main.startAnt(Main.java:235)
[rh-util:dirDiff] 	at org.apache.tools.ant.Main.start(Main.java:198)
[rh-util:dirDiff] 	at org.apache.tools.ant.Main.main(Main.java:286)
[rh-util:dirDiff] Caused by: org.apache.bsf.BSFException: The application script threw an exception: java.io.FileNotFoundException: /Users/bk/.solenopsis/env/DEV/abels/CustomLabels.labels (No such file or directory) BSF info: scriptdef_http://www.redhat.com/util:dirDiff at line: 0 column: columnNo
[rh-util:dirDiff] 	at bsh.util.BeanShellBSFEngine.eval(Unknown Source)
[rh-util:dirDiff] 	at bsh.util.BeanShellBSFEngine.exec(Unknown Source)
[rh-util:dirDiff] 	at org.apache.bsf.BSFManager$6.run(BSFManager.java:493)
[rh-util:dirDiff] 	... 35 more
[rh-util:dirDiff] 

BUILD FAILED
/usr/share/solenopsis/ant/1.1/solenopsis-build.xml:224: The following error occurred while executing this line:
/usr/share/solenopsis/ant/1.1/util/sfdc-util.xml:2272: org.apache.bsf.BSFException: The application script threw an exception: java.io.FileNotFoundException: /Users/bk/.solenopsis/env/DEV/abels/CustomLabels.labels (No such file or directory) BSF info: scriptdef_http://www.redhat.com/util:dirDiff at line: 0 column: columnNo
	at bsh.util.BeanShellBSFEngine.eval(Unknown Source)
	at bsh.util.BeanShellBSFEngine.exec(Unknown Source)
	at org.apache.bsf.BSFManager$6.run(BSFManager.java:493)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.apache.bsf.BSFManager.exec(BSFManager.java:491)
	at org.apache.tools.ant.util.optional.ScriptRunner.executeScript(ScriptRunner.java:98)
	at org.apache.tools.ant.taskdefs.optional.script.ScriptDef.executeScript(ScriptDef.java:349)
	at org.apache.tools.ant.taskdefs.optional.script.ScriptDefBase.execute(ScriptDefBase.java:51)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:68)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.taskdefs.MacroInstance.execute(MacroInstance.java:396)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.Target.execute(Target.java:435)
	at org.apache.tools.ant.Target.performTasks(Target.java:456)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
	at org.apache.tools.ant.Project.executeTarget(Project.java:1376)
	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
	at org.apache.tools.ant.Main.runBuild(Main.java:853)
	at org.apache.tools.ant.Main.startAnt(Main.java:235)
	at org.apache.tools.ant.Main.start(Main.java:198)
	at org.apache.tools.ant.Main.main(Main.java:286)

Total time: 1 minute 28 seconds

**Comment by sfloess** [comment]
@bk-dev - can you share with me your ~/solenopsis.properties file?

There is a known issue if one uses a trailing slash for dirs (I've not yet documented).  For example, mine looks like:

```
solenopsis.ENVIRONMENTS=sfloess dev
solenopsis.env.HOME=/home/sfloess/.solenopsis
solenopsis.env.MASTER=local
solenopsis.env.DEPENDENT=sfloess
solenopsis.env.local.HOME=/home/sfloess/Development/redhat/GSS/CCM/ccm/src
```

As I recall, had I used ```solenopsis.env.local.HOME=/home/sfloess/Development/redhat/GSS/CCM/ccm/src/``` it acts as you describe.

**Comment by sfloess** [comment]
@bk-dev - please look at issue #135.  In particular look at the second bullet point denoted in that issue:

`if we have an ending slash on the property solenopsis.env.local.HOME, we end up chopping off the first character. So "tabs" becomes "abs"`

Additionally, issue #136 discussed denoting this in the documentation.

I'm closing this issue as its been captured.  Please re-open if you think there is another problem.
