### ISSUE TITLE
runAllTests has been removed in API 34.0

### ISSUE THREAD

**Issue by pcon** [solenopsis/Solenopsis#187]
According to the [release notes](http://releasenotes.docs.salesforce.com/en-us/summer15/release-notes/rn_api_meta_new_calls.htm#testlevels):

> The runAllTests deployment option in the DeployOptions object has been removed and is replaced by testLevel.

So, any place we use `runAllTests` we need to check to see if the API version is 34.0+ and if so, not include the `runAllTests='true'` but instead have `testLevel='RunAllTestsInOrg'`

For completeness / consistency sake we could also add `testLevel='NoTestRun'` in the places we were doing `runAllTests='false'` but I think that's a nice to have, not a requirement.

**Comment by sfloess** [comment]
@pcon - if you will, test out branch sfloess_issue-187 - fix should be in place.
