### ISSUE TITLE
Should default to RunLocalTests instead RunAllTestsInOrg

### ISSUE THREAD

**Issue by pcon** [solenopsis/Solenopsis#192]
Issue #187 was filed incorrectly.  Most of the time we should use `RunLocalTests` instead of `RunAllTestsInOrg` since most users do not care about running tests in managed packages.

**Comment by sfloess** [comment]
@pcon want this as an sf.property that defaults to RunLocalTests?

**Comment by pcon** [comment]
No.  I think *maybe* we should add an additional flag to say something like `--include-managed-packages` but I will file an additional issue for that

**Comment by sfloess** [comment]
@pcon - OK so then make the default be `RunLocalTests` until the new issue is filed?

**Comment by pcon** [comment]
@sfloess Yes
