### ISSUE TITLE
When specifying runTest the testLevel should be set to RunSpecifiedTests for api v34.0+

### ISSUE THREAD

**Issue by pcon** [solenopsis/Solenopsis#194]
When specifying `<runTest>...</runTest>` testLevel should be set to `RunSpecifiedTests` instead of `RunAllTestsInOrg`

**Comment by sfloess** [comment]
Fixed in #195.

**Comment by pcon** [comment]
Why did we reopen this?

**Comment by sfloess** [comment]
@pcon - reopened accidentally...  I think we are good now.
