### ISSUE TITLE
Array index out of bounds in createPackageXmlChildren

### ISSUE THREAD

**Issue by jayce1996** [solenopsis/Solenopsis#202]
Following error occurs on delta-push

Switched to branch 'R_US67346'
First, rewinding head to replay your work on top of it...
Applying: US67346 - CSAT ICE esclaations should automatically set ICE owner to case owner's manager

jason@wayreth /devel/ccm/src on ⭠ R_US67346 ⌚ 13:53:47
$ solenopsis delta-push
Could not import "beatbox" library
Buildfile: /usr/share/solenopsis/ant/solenopsis.xml

info:
     [echo] 
     [echo] Solenopsis release version  [1.2-55]
     [echo] Solenopsis version          [1.1]
     [echo] 
     [echo] Ant version                 [Apache Ant(TM) version 1.9.6 compiled on June 29 2015]
     [echo] Java version                [1.8]
     [echo] 		

pull-full:
   [delete] Deleting directory /tmp/jason/solenopsis/1.1/jhird/folder-pull
    [mkdir] Created dir: /tmp/jason/solenopsis/1.1/jhird/folder-pull
     [echo] Generating package.xml
     [echo] 
     [echo] 
     [echo] 				Processing:  [jhird]
     [echo] 
     [echo] 				URL:         [https://test.salesforce.com]
     [echo] 				API:         [34.0]
     [echo] 
     [echo] 				Jar:         [/home/jason/.ant/lib/ant-salesforce.jar]
     [echo] 
     [echo] 			
   [delete] Deleting directory /home/jason/.solenopsis/env/jhird
    [mkdir] Created dir: /home/jason/.solenopsis/env/jhird
[sf:retrieve] Request for a retrieve submitted successfully.
[sf:retrieve] Request ID for the current retrieve task: 09S11000003FOH3EAO
[sf:retrieve] Waiting for server to finish processing the request...
[sf:retrieve] Request Status: Pending
[sf:retrieve] Request Status: InProgress
[sf:retrieve] Request Status: InProgress
[sf:retrieve] Request Status: InProgress
[sf:retrieve] Request Status: InProgress
[sf:retrieve] Request Status: Succeeded
[sf:retrieve] Retrieve warnings (1):
[sf:retrieve] package.xml - Can't retrieve non-customizable CustomObject named: UserLicense
[sf:retrieve] Finished request 09S11000003FOH3EAO successfully.
   [delete] Deleting: /tmp/jason/solenopsis/1.1/jhird/folder-pull/folder-pull.package.xml
      [zip] Building zip: /tmp/jason/solenopsis/1.1/jhird/folder-pull/folder-pull.zip
    [unzip] Expanding: /tmp/jason/solenopsis/1.1/jhird/folder-pull/folder-pull.zip into /home/jason/.solenopsis/env/jhird
[rh-sfdc:transformFiles] WARNING:  No xsl directory found for []
     [echo] 
     [echo]                         Purging ignores is set to [false] - therefore it is skipped!
     [echo] 
     [echo]                         If you want it enabled, ensure the value is not [false].  This
     [echo]                         can be done by defining the environment variable sf.purgeIgnores to true
     [echo]                         or any other value.
     [echo]                     

cached-delta-push:
   [delete] Deleting directory /tmp/jason/solenopsis/1.1/jhird/file-push
    [mkdir] Created dir: /tmp/jason/solenopsis/1.1/jhird/file-push
     [echo] 
     [echo]                         Purging ignores is set to [false] - therefore it is skipped!
     [echo] 
     [echo]                         If you want it enabled, ensure the value is not [false].  This
     [echo]                         can be done by defining the environment variable sf.purgeIgnores to true
     [echo]                         or any other value.
     [echo]                     
     [copy] Copying 1 file to /tmp/jason/solenopsis/1.1/jhird/file-push
     [copy] Copying 1 file to /tmp/jason/solenopsis/1.1/jhird/file-push
     [copy] Copying 1 file to /tmp/jason/solenopsis/1.1/jhird/file-push
     [copy] Copying 1 file to /tmp/jason/solenopsis/1.1/jhird/file-push
     [copy] Copying 1 file to /tmp/jason/solenopsis/1.1/jhird/file-push
     [copy] Copying 1 file to /tmp/jason/solenopsis/1.1/jhird/file-push
     [copy] Copying 1 file to /tmp/jason/solenopsis/1.1/jhird/file-push
     [copy] Copying 1 file to /tmp/jason/solenopsis/1.1/jhird/file-push
     [copy] Copying 1 file to /tmp/jason/solenopsis/1.1/jhird/file-push
     [copy] Copying 1 file to /tmp/jason/solenopsis/1.1/jhird/file-push
     [copy] Copying 1 file to /tmp/jason/solenopsis/1.1/jhird/file-push
     [copy] Copying 1 file to /tmp/jason/solenopsis/1.1/jhird/file-push
     [copy] Copying 1 file to /tmp/jason/solenopsis/1.1/jhird/file-push
     [copy] Copying 1 file to /tmp/jason/solenopsis/1.1/jhird/file-push
     [copy] Copying 1 file to /tmp/jason/solenopsis/1.1/jhird/file-push
     [copy] Copying 1 file to /tmp/jason/solenopsis/1.1/jhird/file-push
     [copy] Copying 1 file to /tmp/jason/solenopsis/1.1/jhird/file-push
     [copy] Copying 1 file to /tmp/jason/solenopsis/1.1/jhird/file-push
     [copy] Copying 1 file to /tmp/jason/solenopsis/1.1/jhird/file-push
     [copy] Copying 1 file to /tmp/jason/solenopsis/1.1/jhird/file-push
     [copy] Copying 1 file to /tmp/jason/solenopsis/1.1/jhird/file-push
     [copy] Copying 1 file to /tmp/jason/solenopsis/1.1/jhird/file-push
     [copy] Copying 1 file to /tmp/jason/solenopsis/1.1/jhird/file-push
     [copy] Copying 1 file to /tmp/jason/solenopsis/1.1/jhird/file-push
     [copy] Copying 1 file to /tmp/jason/solenopsis/1.1/jhird/file-push
     [copy] Copying 2 files to /tmp/jason/solenopsis/1.1/jhird/file-push
     [copy] Copying 2 files to /tmp/jason/solenopsis/1.1/jhird/file-push
     [copy] Copying 2 files to /tmp/jason/solenopsis/1.1/jhird/file-push
     [copy] Copying 2 files to /tmp/jason/solenopsis/1.1/jhird/file-push
     [copy] Copying 1 file to /tmp/jason/solenopsis/1.1/jhird/file-push
     [copy] Copying 1 file to /tmp/jason/solenopsis/1.1/jhird/file-push
     [copy] Copying 1 file to /tmp/jason/solenopsis/1.1/jhird/file-push
     [copy] Copying 1 file to /tmp/jason/solenopsis/1.1/jhird/file-push
     [copy] Copying 1 file to /tmp/jason/solenopsis/1.1/jhird/file-push
     [copy] Copying 1 file to /tmp/jason/solenopsis/1.1/jhird/file-push
     [copy] Copying 1 file to /tmp/jason/solenopsis/1.1/jhird/file-push
     [copy] Copying 1 file to /tmp/jason/solenopsis/1.1/jhird/file-push
     [copy] Copying 1 file to /tmp/jason/solenopsis/1.1/jhird/file-push
     [copy] Copying 1 file to /tmp/jason/solenopsis/1.1/jhird/file-push
     [copy] Copying 1 file to /tmp/jason/solenopsis/1.1/jhird/file-push
     [copy] Copying 1 file to /tmp/jason/solenopsis/1.1/jhird/file-push
     [copy] Copying 1 file to /tmp/jason/solenopsis/1.1/jhird/file-push
     [copy] Copying 2 files to /tmp/jason/solenopsis/1.1/jhird/file-push
     [copy] Copying 1 file to /tmp/jason/solenopsis/1.1/jhird/file-push
     [copy] Copying 1 file to /tmp/jason/solenopsis/1.1/jhird/file-push
     [copy] Copying 1 file to /tmp/jason/solenopsis/1.1/jhird/file-push
     [copy] Copying 1 file to /tmp/jason/solenopsis/1.1/jhird/file-push
     [copy] Copying 1 file to /tmp/jason/solenopsis/1.1/jhird/file-push
     [copy] Copying 1 file to /tmp/jason/solenopsis/1.1/jhird/file-push
     [copy] Copying 1 file to /tmp/jason/solenopsis/1.1/jhird/file-push
     [copy] Copying 1 file to /tmp/jason/solenopsis/1.1/jhird/file-push
     [copy] Copying 1 file to /tmp/jason/solenopsis/1.1/jhird/file-push
     [copy] Copying 1 file to /tmp/jason/solenopsis/1.1/jhird/file-push
     [copy] Copying 1 file to /tmp/jason/solenopsis/1.1/jhird/file-push
     [copy] Copying 1 file to /tmp/jason/solenopsis/1.1/jhird/file-push
     [copy] Copying 1 file to /tmp/jason/solenopsis/1.1/jhird/file-push
     [copy] Copying 1 file to /tmp/jason/solenopsis/1.1/jhird/file-push
     [copy] Copying 1 file to /tmp/jason/solenopsis/1.1/jhird/file-push
     [copy] Copying 1 file to /tmp/jason/solenopsis/1.1/jhird/file-push
     [copy] Copying 1 file to /tmp/jason/solenopsis/1.1/jhird/file-push
     [copy] Copying 1 file to /tmp/jason/solenopsis/1.1/jhird/file-push
     [copy] Copying 1 file to /tmp/jason/solenopsis/1.1/jhird/file-push
     [copy] Copying 1 file to /tmp/jason/solenopsis/1.1/jhird/file-push
     [copy] Copying 1 file to /tmp/jason/solenopsis/1.1/jhird/file-push
     [copy] Copying 1 file to /tmp/jason/solenopsis/1.1/jhird/file-push
     [copy] Copying 1 file to /tmp/jason/solenopsis/1.1/jhird/file-push
     [copy] Copying 1 file to /tmp/jason/solenopsis/1.1/jhird/file-push
     [copy] Copying 1 file to /tmp/jason/solenopsis/1.1/jhird/file-push
     [copy] Copying 1 file to /tmp/jason/solenopsis/1.1/jhird/file-push
     [copy] Copying 1 file to /tmp/jason/solenopsis/1.1/jhird/file-push
     [copy] Copying 1 file to /tmp/jason/solenopsis/1.1/jhird/file-push
     [copy] Copying 1 file to /tmp/jason/solenopsis/1.1/jhird/file-push
     [copy] Copying 1 file to /tmp/jason/solenopsis/1.1/jhird/file-push
     [copy] Copying 1 file to /tmp/jason/solenopsis/1.1/jhird/file-push
     [copy] Copying 1 file to /tmp/jason/solenopsis/1.1/jhird/file-push
     [copy] Copying 1 file to /tmp/jason/solenopsis/1.1/jhird/file-push
     [copy] Copying 1 file to /tmp/jason/solenopsis/1.1/jhird/file-push
     [copy] Copying 1 file to /tmp/jason/solenopsis/1.1/jhird/file-push
     [copy] Copying 1 file to /tmp/jason/solenopsis/1.1/jhird/file-push
     [copy] Copying 1 file to /tmp/jason/solenopsis/1.1/jhird/file-push
     [copy] Copying 1 file to /tmp/jason/solenopsis/1.1/jhird/file-push
     [copy] Copying 1 file to /tmp/jason/solenopsis/1.1/jhird/file-push
     [copy] Copying 1 file to /tmp/jason/solenopsis/1.1/jhird/file-push
     [copy] Copying 1 file to /tmp/jason/solenopsis/1.1/jhird/file-push
     [copy] Copying 1 file to /tmp/jason/solenopsis/1.1/jhird/file-push
     [copy] Copying 1 file to /tmp/jason/solenopsis/1.1/jhird/file-push
     [copy] Copying 1 file to /tmp/jason/solenopsis/1.1/jhird/file-push
     [copy] Copying 1 file to /tmp/jason/solenopsis/1.1/jhird/file-push
[rh-sfdc:createPackageXmlChildren] Aug 27, 2015 1:56:00 PM org.apache.bsf.BSFManager exec
[rh-sfdc:createPackageXmlChildren] SEVERE: Exception :
[rh-sfdc:createPackageXmlChildren] java.security.PrivilegedActionException: org.apache.bsf.BSFException: The application script threw an exception: java.lang.ArrayIndexOutOfBoundsException BSF info: scriptdef_http://www.redhat.com/sfdc:createPackageXmlChildren at line: 0 column: columnNo
[rh-sfdc:createPackageXmlChildren] 	at java.security.AccessController.doPrivileged(Native Method)
[rh-sfdc:createPackageXmlChildren] 	at org.apache.bsf.BSFManager.exec(BSFManager.java:491)
[rh-sfdc:createPackageXmlChildren] 	at org.apache.tools.ant.util.optional.ScriptRunner.executeScript(ScriptRunner.java:98)
[rh-sfdc:createPackageXmlChildren] 	at org.apache.tools.ant.taskdefs.optional.script.ScriptDef.executeScript(ScriptDef.java:349)
[rh-sfdc:createPackageXmlChildren] 	at org.apache.tools.ant.taskdefs.optional.script.ScriptDefBase.execute(ScriptDefBase.java:51)
[rh-sfdc:createPackageXmlChildren] 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
[rh-sfdc:createPackageXmlChildren] 	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
[rh-sfdc:createPackageXmlChildren] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[rh-sfdc:createPackageXmlChildren] 	at java.lang.reflect.Method.invoke(Method.java:497)
[rh-sfdc:createPackageXmlChildren] 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
[rh-sfdc:createPackageXmlChildren] 	at org.apache.tools.ant.Task.perform(Task.java:348)
[rh-sfdc:createPackageXmlChildren] 	at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:68)
[rh-sfdc:createPackageXmlChildren] 	at net.sf.antcontrib.logic.IfTask.execute(IfTask.java:197)
[rh-sfdc:createPackageXmlChildren] 	at sun.reflect.GeneratedMethodAccessor26.invoke(Unknown Source)
[rh-sfdc:createPackageXmlChildren] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[rh-sfdc:createPackageXmlChildren] 	at java.lang.reflect.Method.invoke(Method.java:497)
[rh-sfdc:createPackageXmlChildren] 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
[rh-sfdc:createPackageXmlChildren] 	at org.apache.tools.ant.TaskAdapter.execute(TaskAdapter.java:155)
[rh-sfdc:createPackageXmlChildren] 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
[rh-sfdc:createPackageXmlChildren] 	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
[rh-sfdc:createPackageXmlChildren] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[rh-sfdc:createPackageXmlChildren] 	at java.lang.reflect.Method.invoke(Method.java:497)
[rh-sfdc:createPackageXmlChildren] 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
[rh-sfdc:createPackageXmlChildren] 	at org.apache.tools.ant.Task.perform(Task.java:348)
[rh-sfdc:createPackageXmlChildren] 	at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:68)
[rh-sfdc:createPackageXmlChildren] 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
[rh-sfdc:createPackageXmlChildren] 	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
[rh-sfdc:createPackageXmlChildren] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[rh-sfdc:createPackageXmlChildren] 	at java.lang.reflect.Method.invoke(Method.java:497)
[rh-sfdc:createPackageXmlChildren] 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
[rh-sfdc:createPackageXmlChildren] 	at org.apache.tools.ant.Task.perform(Task.java:348)
[rh-sfdc:createPackageXmlChildren] 	at org.apache.tools.ant.taskdefs.MacroInstance.execute(MacroInstance.java:396)
[rh-sfdc:createPackageXmlChildren] 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
[rh-sfdc:createPackageXmlChildren] 	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
[rh-sfdc:createPackageXmlChildren] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[rh-sfdc:createPackageXmlChildren] 	at java.lang.reflect.Method.invoke(Method.java:497)
[rh-sfdc:createPackageXmlChildren] 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
[rh-sfdc:createPackageXmlChildren] 	at org.apache.tools.ant.Task.perform(Task.java:348)
[rh-sfdc:createPackageXmlChildren] 	at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:68)
[rh-sfdc:createPackageXmlChildren] 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
[rh-sfdc:createPackageXmlChildren] 	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
[rh-sfdc:createPackageXmlChildren] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[rh-sfdc:createPackageXmlChildren] 	at java.lang.reflect.Method.invoke(Method.java:497)
[rh-sfdc:createPackageXmlChildren] 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
[rh-sfdc:createPackageXmlChildren] 	at org.apache.tools.ant.Task.perform(Task.java:348)
[rh-sfdc:createPackageXmlChildren] 	at org.apache.tools.ant.taskdefs.MacroInstance.execute(MacroInstance.java:396)
[rh-sfdc:createPackageXmlChildren] 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
[rh-sfdc:createPackageXmlChildren] 	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
[rh-sfdc:createPackageXmlChildren] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[rh-sfdc:createPackageXmlChildren] 	at java.lang.reflect.Method.invoke(Method.java:497)
[rh-sfdc:createPackageXmlChildren] 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
[rh-sfdc:createPackageXmlChildren] 	at org.apache.tools.ant.Task.perform(Task.java:348)
[rh-sfdc:createPackageXmlChildren] 	at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:68)
[rh-sfdc:createPackageXmlChildren] 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
[rh-sfdc:createPackageXmlChildren] 	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
[rh-sfdc:createPackageXmlChildren] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[rh-sfdc:createPackageXmlChildren] 	at java.lang.reflect.Method.invoke(Method.java:497)
[rh-sfdc:createPackageXmlChildren] 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
[rh-sfdc:createPackageXmlChildren] 	at org.apache.tools.ant.Task.perform(Task.java:348)
[rh-sfdc:createPackageXmlChildren] 	at org.apache.tools.ant.taskdefs.MacroInstance.execute(MacroInstance.java:396)
[rh-sfdc:createPackageXmlChildren] 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
[rh-sfdc:createPackageXmlChildren] 	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
[rh-sfdc:createPackageXmlChildren] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[rh-sfdc:createPackageXmlChildren] 	at java.lang.reflect.Method.invoke(Method.java:497)
[rh-sfdc:createPackageXmlChildren] 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
[rh-sfdc:createPackageXmlChildren] 	at org.apache.tools.ant.Task.perform(Task.java:348)
[rh-sfdc:createPackageXmlChildren] 	at org.apache.tools.ant.Target.execute(Target.java:435)
[rh-sfdc:createPackageXmlChildren] 	at org.apache.tools.ant.Target.performTasks(Target.java:456)
[rh-sfdc:createPackageXmlChildren] 	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
[rh-sfdc:createPackageXmlChildren] 	at org.apache.tools.ant.Project.executeTarget(Project.java:1376)
[rh-sfdc:createPackageXmlChildren] 	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
[rh-sfdc:createPackageXmlChildren] 	at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
[rh-sfdc:createPackageXmlChildren] 	at org.apache.tools.ant.Main.runBuild(Main.java:853)
[rh-sfdc:createPackageXmlChildren] 	at org.apache.tools.ant.Main.startAnt(Main.java:235)
[rh-sfdc:createPackageXmlChildren] 	at org.apache.tools.ant.Main.start(Main.java:198)
[rh-sfdc:createPackageXmlChildren] 	at org.apache.tools.ant.Main.main(Main.java:286)
[rh-sfdc:createPackageXmlChildren] Caused by: org.apache.bsf.BSFException: The application script threw an exception: java.lang.ArrayIndexOutOfBoundsException BSF info: scriptdef_http://www.redhat.com/sfdc:createPackageXmlChildren at line: 0 column: columnNo
[rh-sfdc:createPackageXmlChildren] 	at bsh.util.BeanShellBSFEngine.eval(Unknown Source)
[rh-sfdc:createPackageXmlChildren] 	at bsh.util.BeanShellBSFEngine.exec(Unknown Source)
[rh-sfdc:createPackageXmlChildren] 	at org.apache.bsf.BSFManager$6.run(BSFManager.java:493)
[rh-sfdc:createPackageXmlChildren] 	... 76 more
[rh-sfdc:createPackageXmlChildren] 

BUILD FAILED
/usr/share/solenopsis/ant/1.1/solenopsis-build.xml:224: The following error occurred while executing this line:
/usr/share/solenopsis/ant/1.1/util/sfdc-util.xml:2787: The following error occurred while executing this line:
/usr/share/solenopsis/ant/1.1/util/sfdc-util.xml:2406: The following error occurred while executing this line:
/usr/share/solenopsis/ant/1.1/util/sfdc-util.xml:2408: org.apache.bsf.BSFException: The application script threw an exception: java.lang.ArrayIndexOutOfBoundsException BSF info: scriptdef_http://www.redhat.com/sfdc:createPackageXmlChildren at line: 0 column: columnNo
	at bsh.util.BeanShellBSFEngine.eval(Unknown Source)
	at bsh.util.BeanShellBSFEngine.exec(Unknown Source)
	at org.apache.bsf.BSFManager$6.run(BSFManager.java:493)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.apache.bsf.BSFManager.exec(BSFManager.java:491)
	at org.apache.tools.ant.util.optional.ScriptRunner.executeScript(ScriptRunner.java:98)
	at org.apache.tools.ant.taskdefs.optional.script.ScriptDef.executeScript(ScriptDef.java:349)
	at org.apache.tools.ant.taskdefs.optional.script.ScriptDefBase.execute(ScriptDefBase.java:51)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:68)
	at net.sf.antcontrib.logic.IfTask.execute(IfTask.java:197)
	at sun.reflect.GeneratedMethodAccessor26.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.TaskAdapter.execute(TaskAdapter.java:155)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:68)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.taskdefs.MacroInstance.execute(MacroInstance.java:396)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:68)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.taskdefs.MacroInstance.execute(MacroInstance.java:396)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:68)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.taskdefs.MacroInstance.execute(MacroInstance.java:396)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.Target.execute(Target.java:435)
	at org.apache.tools.ant.Target.performTasks(Target.java:456)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
	at org.apache.tools.ant.Project.executeTarget(Project.java:1376)
	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
	at org.apache.tools.ant.Main.runBuild(Main.java:853)
	at org.apache.tools.ant.Main.startAnt(Main.java:235)
	at org.apache.tools.ant.Main.start(Main.java:198)
	at org.apache.tools.ant.Main.main(Main.java:286)

Total time: 1 minute 49 seconds

jason@wayreth /devel/ccm/src on ⭠ R_US67346 ⌚ 13:56:01

**Comment by sfloess** [comment]
After working with Jason, we discovered his local cache in ~/.solenopsis/env was bad.  By removing the directory, the problem went away.

I am, however, putting in some defensive coding and will emit a warning.
