### ISSUE TITLE
Delta-push does not change API versions of Visualforce pages

### ISSUE THREAD

**Issue by pcon** [solenopsis/Solenopsis#205]
Steps to reproduce

1. Create Visualforce page with a lower API version
2. Push to sandbox
3. Change the API version in the -meta.xml file
4. Run `delta-push`

After inspecting the page in Salesforce or doing a `pull-full-to-master` you'll see that the metadata version is not updated.  It *does not* update the metadata version if the related file has changed.

**Comment by sfloess** [comment]
@pcon,

This is an "interesting" problem.  I noted I was ignoring "meta.xml" files and that removing that from the code did, in fact, push out the corresponding meta.xml file.  However, in the SFDC UI, the version number was not rev'd as expected.  I think the fix here is going to be to treat these files as pairs.

I inserted an XML comment in a visual force page and sure enough the version bumped as expected.

**Comment by sfloess** [comment]
@pcon,

Mind testing my branch ```sfloess_issue-205```?

I tested this locally as follows:
* only -meta.xml change:  both the [file].page and [file].page-meta.xml pushed and updated the version in SFDC.
* both [file].page and [file].page-meta.xml changed - both pushed out and the version updated in SFDC.

**Comment by pcon** [comment]
Confirmed.  Works for me.

**Comment by sfloess** [comment]
@pcon - I'll get this into master tomorrow...
