### ISSUE TITLE
Allow XSLs to be applied only on pull operations

### ISSUE THREAD

**Issue by pcon** [solenopsis/Solenopsis#208]
We currently use Solenopsis's ability to replace `@{variablename}` when doing pushes.  However when pulling these get replaced by the current value of the host.  It would be nice to be able to apply an XSL to replace these back with their variable names.  The current XSLs get applied both one pull as well as push so they cannot be used.

**Comment by sfloess** [comment]
@pcon - fix is in.  I've done some testing both for push and pull.  If you will test the branch sfloess_issue-208 and ack this, I will merge to master.

Basically, on any:
* pull, if an XSL exists named ```[file]_pull.xsl```, it will be applied.
* push, if any XSL exists named ```[file]_push.xsl```, it will be applied.
* any push or pull, an xsl file exists, it will be applied.
