### ISSUE TITLE
Support XSL operations on -meta.xml files

### ISSUE THREAD

**Issue by pcon** [solenopsis/Solenopsis#209]
It would be nice if we could perform the same XSL transforms on the -meta.xml files.  For example:

`Contact_View.page-meta.xml`
```xml
<?xml version="1.0" encoding="UTF-8"?>
<ApexPage xmlns="http://soap.sforce.com/2006/04/metadata">
    <apiVersion>18.0</apiVersion>
    <availableInTouch>false</availableInTouch>
    <confirmationTokenRequired>false</confirmationTokenRequired>
    <label>Contact View</label>
    <packageVersions>
        <majorNumber>2</majorNumber>
        <minorNumber>13</minorNumber>
        <namespace>package_namespace</namespace>
    </packageVersions>
</ApexPage>
```

Applying an XSL to remove the `packageVersion` stanza.  This is most useful on the pull operations, so #208 should be supported.

**Comment by sfloess** [comment]
@pcon - this works now my friend!

I just added the following XSLT (denoted as Contact_View.page-meta_pull.xsl):

```xslt
<?xml version="1.0"?>
<xsl:transform version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:sfdc="http://soap.sforce.com/2006/04/metadata">
	<xsl:output method="xml" version="1.0" indent="yes"/>

	<xsl:template match="/">
		<xsl:apply-templates select="sfdc:ApexPage"/>
	</xsl:template>

	<xsl:template match="sfdc:ApexPage">
		<xsl:text></xsl:text>

		<xsl:copy>
			<xsl:apply-templates mode="copy-mode"/>
		</xsl:copy>
	</xsl:template>

    <xsl:template match="sfdc:packageVersions" mode="copy-mode">
        hello world
    </xsl:template>

	<xsl:template match="*" mode="copy-mode">
		<xsl:copy-of select="."/>
	</xsl:template>
</xsl:transform>
```

Performing a ```bsolenopsis pull-full```, I see this in my console:

```
[rh-sfdc:transformFiles] Transforming [/home/sfloess/.solenopsis/env/sfloess/pages/Contact_View.page-meta.xml]
[rh-sfdc:transformFiles]      XSL [/home/sfloess/Development/redhat/engineering/ccm/xslt/solenopsis/pages/Contact_View.page-meta_pull.xsl]
[rh-sfdc:transformFiles]      Time to transform [1 ms]
```

In looking at the resultant transform, I see:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<ApexPage xmlns="http://soap.sforce.com/2006/04/metadata">
    <apiVersion>18.0</apiVersion>
    <availableInTouch>false</availableInTouch>
    <confirmationTokenRequired>false</confirmationTokenRequired>
    <label>Contact View</label>
        hello world
    
</ApexPage>
```

If you simply create the appropriate XSLTs and name them "close to" the original file name, this will just work :)  For example:
* pulls - name the xslt ```[file name]_pull.xsl```
* pushes - name the xslt ```[file name]_push.xsl```
* push or pull - name the xslt ```[file name].xsl```

The important take-away is we honor "most of the file name" minus the ending extension.  Here your original required file name is ```Contact_View.page-meta.xml```.  So ommitting ```.xml``` but keeping the "base" file name ```Contact_View.page-meta[_push | _pull | nothing].xsl``` will do the needful.

If you really want to remove the ```packageVersions``` element, the XSLT is:

```xsl
<?xml version="1.0"?>
<xsl:transform version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:sfdc="http://soap.sforce.com/2006/04/metadata">
	<xsl:output method="xml" version="1.0" indent="yes"/>

	<xsl:template match="/">
		<xsl:apply-templates select="sfdc:ApexPage"/>
	</xsl:template>

	<xsl:template match="sfdc:ApexPage">
		<xsl:text></xsl:text>

		<xsl:copy>
			<xsl:apply-templates mode="copy-mode"/>
		</xsl:copy>
	</xsl:template>

    <xsl:template match="sfdc:packageVersions" mode="copy-mode"/>

	<xsl:template match="*" mode="copy-mode">
		<xsl:copy-of select="."/>
	</xsl:template>
</xsl:transform>
```

_Will await your confirmation to close..._

PS - sorry this took so long for me to review.  I had to go back and understand what I did to solve #208.

**Comment by pcon** [comment]
Yep, this works.  I'm a moron on two fronts.  First my XSL was incorrect and second I had it named `.xml` not `.xsl`
