### ISSUE TITLE
Missing file-destructive-push in python script

### ISSUE THREAD

**Issue by lordarcy** [solenopsis/Solenopsis#219]
The solenopsis python script is missing the file-destructive-push option. This works in bsolenopsis and is present as a target in the 1.1 version of solenopsis-build.xml.

**Comment by pcon** [comment]
@lordarcy did you ever resubmit the PR for this for us to merge into master?

**Comment by pcon** [comment]
This was done with 374dc5bfd09cee08aa1d0de08f739ed476de1032 to fix #248
