### ISSUE TITLE
command line argument for solenopsis.properties file

### ISSUE THREAD

**Issue by Sagar-Shirke** [solenopsis/Solenopsis#222]
Often we work on more than one issues at a time and there is need to push each change to different sandbox.

Therefore it would be great if a command line argument is provided to solenopsis to use different solenopsis.properties file so that each change can be pushed to different sandbox.

**Comment by pcon** [comment]
This will first require modifying the ant script to allow overriding of the property file.  Then we can modify the wrapper script to allow it.

**Comment by sfloess** [comment]
@Sagar-Shirke, is there a reason you need different ```solenopsis.properties``` files vs defining all the sandboxes you use in your ```solenopsis.properties``` file's ```solenopsis.ENVIRONMENTS```?

You can then denote a different ```solenopsis.env.DEPENDENT``` on each call.  For example let's say you had three sandboxes:  ```foo```, ```bar```, and ```alpha```

The ```solenopsis.properties``` file will contain:

```properties
solenopsis.ENVIRONMENTS=foo bar alpha
```

Then one can perform:
* ```solenopsis -e foo push```
* ```solenopsis -e bar push```
* ```solenopsis -e alpha push```

Doesn't this meet the behavior as requested?

**Comment by Sagar-Shirke** [comment]
@sfloess , This option will definitely work if I am using same git source path for different sandboxes. However, I have different git source directories for different sandboxes. This is because I work for multiple issues at the same time. So changes are not committed many times.

So I have to rename my solenopis.properties file each time to push changes to different sandboxes from different source directories.

**Comment by sfloess** [comment]
@Sagar-Shirke, you can still do as I mentioned but denote those too :)  There is a property entitles ```solenopsis.env.master``` and ```solenopsis.env.[name].HOME```

You should be able to define each of those for each git source directory.

I'm not sure the exact ```solenopsis``` command line options, but using ```bsolenopsis```, I'd simply do this (assuming I have ```solenopsis.env.MASTER=local``` defined in ```~/solenopsis.properties```:

```bsolenopsis -Dsolenopsis.env.local.HOME=/path/to/one/git/dir/1 ...```
...
```bsolenopsis -Dsolenopsis.env.local.HOME=/path/to/one/git/dir/N ...```

**Comment by pcon** [comment]
You can use the `-l` option with solenopsis to define the `solenopsis.env.local.HOME`

**Comment by sfloess** [comment]
@Sagar-Shirke - are you fine with the above suggestions?  I'd like to close this issue if possible.

**Comment by Sagar-Shirke** [comment]
Yes @sfloess 
You can close the issue.

**Comment by sfloess** [comment]
@Sagar-Shirke - thank you!

**Comment by pcon** [comment]
I'd like us to re-evaluate something related to this issue.  Now that I am working in multiple orgs each with their own src dir, ignore files and xslt dirs, it would be nice if we could provide the functionality that @Sagar-Shirke mentioned but do it via the environment configuration.  I would see the following hierarchy

command-line -> environment -> solenopsis.properties -> solenopsis

So if you were to have the following files

_$HOME/solenopsis.properties_
```text
solenopsis.env.local.HOME=/home/pcon/devel/sandbox1/src/
```

_$HOME/.solenopsis/credentials/sandbox2.properties_
```text
solenopsis.env.local.HOME=/home/pcon/devel/sandbox2/src/
```

And you ran `solenopsis -e sandbox2 pull-full-to-master` then the `/home/pcon/devel/sandbox2/src/` directory would be used.  The same applies to sf.ignoreFile and sf.xslDir

**Comment by sfloess** [comment]
@pcon,

I'll do my best to review this (and hopefully) work on it this weekend :+1:

**Comment by sfloess** [comment]
@pcon - I think there is a much simpler solution to all of this.  If we simply add one more property (something like ```sf.env```) that default to ```${HOME}/solenopsis.properties```, you'd be able to lump all your configurations together in one property file per setup.

**Comment by sfloess** [comment]
@pcon - I just pushed out branch ```sfloess_issue-222```.  Basically if you define a ```sf.env``` and the value is a properties file, it will use that over ```${HOME}/solenopsis.properties``` (otherwise it defaults to that value).

We can discuss if we want to shorten the notation.  For example, assume that value _always_ exists in ```${HOME}``` and is a properties file.  So, for example if ```sf.env=foo```, it'd use ```${HOME}/foo.properties```.

**Comment by pcon** [comment]
I think what would be the best thing from a user experience is if we add a new directory `${solenopsis.env.HOME}/environments/` and if `${ENV}.properties` exists in it we use it's variables instead.  I could be convinced that this overrides the stuff in the base `solenopsis.properties` file or it completely replaces all properties.  Whichever is easiest.

**Comment by sfloess** [comment]
@pcon - sounds good to me.  Will try to get this done this weekend :+1:

**Comment by sfloess** [comment]
@pcon - all set.  Try out my branch now:  ```sfloess_issue-222```.

I went with having the user defined new property file override what's in ```${HOME}/solenopsis.properties```.  I still stuck with the property ```sf.env``` but will load ```${solenopsis.env.HOME}/environments/${sf.env}``` - and it's fine if that property isn't defined or the property file is missing (meaning we will not blow-up).

If you'd rather a different property - no problem at all :)

When this is all done, I will update the wiki to reflect this new functionality.
