### ISSUE TITLE
file-push does not find files to push when the folder has a $ in it

### ISSUE THREAD

**Issue by pcon** [solenopsis/Solenopsis#225]
When trying to push a file with a $ in it, file-push does not work as expected.  For example

```
email/unfiled$public/ChangePwdEmail.email
```

file push outputs

```
 [copy] Warning: Could not find resource file "/home/pcon/ccm/src/email/unfiled/ChangePwdEmail.email" to copy.
```

It appears that it's trying to do an expansion of the `$public` variable to nothing

**Comment by sfloess** [comment]
@pcon,

Are you using single quotes or double quotes?

For example if I executed this:
```bsolenosis -D sf.files2push="email/unifiled$public/ChangePwdEmail.email" file-push```

The OS is stepping in and expanding it just as if I'd done this:

```bsolenosis -D sf.files2push="email/unifiled${public}/ChangePwdEmail.email" file-push```

I'm betting single quotes would fix the issue:

```bsolenosis -D sf.files2push='email/unifiled$public/ChangePwdEmail.email' file-push```

**Comment by sfloess** [comment]
As a follow-up...

Performing:  ```bsolenopsis -Dsf.files2push="email/unifiled$public/ChangePwdEmail.email" file-push```

Yields:  ```Requested Push:            [email/unifiled/ChangePwdEmail.email]```

Whereas performing:  ```bsolenopsis -Dsf.files2push='email/unifiled$public/ChangePwdEmail.email' file-push```

Yields:  ```Requested Push:            [email/unifiled$public/ChangePwdEmail.email]```
