### ISSUE TITLE
OAuth2 SFDC and Solenopsis

### ISSUE THREAD

**Issue by rdamron** [solenopsis/Solenopsis#228]
Is it possible to use solenopsis when our salesforce org is set up to use OAuth2 and a federated identity provider?

**Comment by pcon** [comment]
Solenopsis is built on top of the Salesforce ANT Migration Tool.  This tool only supports username/password auth.  Because of the Solenopsis does not support any other authorization strategies.

**Comment by rdamron** [comment]
My apologies I was confused at the source of my problem. I will open another issue if needed after further investigation.
