### ISSUE TITLE
Using without a security token.

### ISSUE THREAD

**Issue by rdamron** [solenopsis/Solenopsis#229]
Is it possible to use this tool if my Org does not support a security token? I have created an integration user and can use the ant migration tool with just my username and password. 

Is it possible to omit this as we utilize OAuth2 for most users, by enabling this it appears we can not create tokens.

**Comment by brookesy2** [comment]
In instances where a token is mandatory just split your password across both fields.

**Comment by rdamron** [comment]
what do you mean by "split"?

**Comment by brookesy2** [comment]
Lets pretend your password is SuperPassword1234!

password =SuperPassword
Token =1234!

**Comment by rdamron** [comment]
Ok so a token and password are just appended in the end. Got it! Thanks!
