### ISSUE TITLE
An empty ignoreFile causes all files to be ignored

### ISSUE THREAD

**Issue by pcon** [solenopsis/Solenopsis#243]
If an `ignoreFile` is set and the contents of that file are empty, then all files that are being pushed will be ignored

**Comment by sfloess** [comment]
@pcon - which command were you using?  I tried both cached-delta-push and push with an empty ignore file - looks like the deploy.zip does contain files.  Mind calling out exactly what you did?

**Comment by pcon** [comment]
I just did

1. `touch /tmp/ignore`
2. set `sf.ignoreFile = /tmp/ignore`
3. Change a file (TestUtils.cls in my case)
4. Run `solenopsis git-push`

The output is as follows

```text
BUILD FAILED
/usr/share/solenopsis/ant/1.1/solenopsis-build.xml:189: The following error occurred while executing this line:
/usr/share/solenopsis/ant/1.1/util/sfdc-util.xml:3072: The following error occurred while executing this line:
/usr/share/solenopsis/ant/1.1/util/sfdc-util.xml:3074: The following error occurred while executing this line:
/usr/share/solenopsis/ant/1.1/util/sfdc-util.xml:2600: The following error occurred while executing this line:
/usr/share/solenopsis/ant/1.1/util/sfdc-util.xml:2613: The following error occurred while executing this line:
/usr/share/solenopsis/ant/1.1/util/sfdc-util.xml:2615: You are attempting to push file(s) that are to be ignored:  classes/TestUtils.cls, classes/TestUtils.cls-meta.xml, package.xml
```

**Comment by sfloess** [comment]
@pcon - thanks buddy!

**Comment by pcon** [comment]
@sfloess Looks like this broke the ignore file stuff.  It seems to no load it at all and I am able to push files that are on the ignore list.  Reverting the `rhutil:ifNotEqual` results in it ignoring the files again.

**Comment by sfloess** [comment]
@pcon - crap...sorry about that...  I'll try to "fix" it again :(

**Comment by sfloess** [comment]
@pcon - finally this ought to be fixed now...
