### ISSUE TITLE
Question: Run all test during deployment in a sandbox environment?

### ISSUE THREAD

**Issue by LopezRegaladoFj** [solenopsis/Solenopsis#245]
Question: How can I run all the test during the deployment in a sandbox environment?

I have generated a dumpFile using the property `sf.dumpFiles` and `sf.runAllTest=true` in order to check the details. In the file generated after run `solenopsis push` I can view the property `testLevel=RunLocalTests`, If a run this build.xml directly using the ant command:
`ant -f [patch to build.xml]` **all test are running** in the sandbox deployment.

The behaviour is not the same using `solenopsis push`, in this case no test are running during the deployment

**Comment by LopezRegaladoFj** [comment]
I have view in `macrodef name="push"` there is not set the param `testLevel` in the `sf:deploy`

`                    <sf:deploy username="${push.USERNAME}" password="${push.PASSWORD}" serverurl="${push.URL}" zipFile="${push.DEPLOY_FILE}" trace="@{trace}" runAllTests="@{runAllTests}" maxPoll="@{maxPoll}" allowMissingFiles="@{allowMissingFiles}" logType="@{logType}" checkOnly="@{checkOnly}" ignoreWarnings="@{ignoreWarnings}"/>`

**Comment by sfloess** [comment]
@LopezRegaladoFj - which API version are you using?

Also, looks like we maybe missing the `testLevel` param?  If so, I can add that pretty quickly...

**Comment by sfloess** [comment]
@LopezRegaladoFj - oops nevermind...I see what you mean now:  https://developer.salesforce.com/docs/atlas.en-us.daas.meta/daas/forcemigrationtool_deploy.htm

This should be a simple fix to add that param...

Sorry about that - and nice catch...  I do very little to no SFDC development any longer.  I try to stay up on things - but this is one of many open source projects I am working :)

**Comment by LopezRegaladoFj** [comment]
your work is awesome @sfloess! thank you so much!!

**Comment by sfloess** [comment]
@LopezRegaladoFj - oh you are very welcome!  Thanks for using solenopsis!  :)

**Comment by sfloess** [comment]
@LopezRegaladoFj - I added an "sf.testLevel" property.  If set, that's the level of tests that will be run (per https://developer.salesforce.com/docs/atlas.en-us.daas.meta/daas/forcemigrationtool_deploy.htm).

**Comment by sfloess** [comment]
@pcon - did that last night :) ... #247
