### ISSUE TITLE
dirDiff is comparing files replacing all special characters

### ISSUE THREAD

**Issue by LopezRegaladoFj** [solenopsis/Solenopsis#246]
Checking the method `solenopsis delta-push`we have found that if we changes some file only adding a space this method returns that two files are equals and it is not right.

**rh-util.xml**

            boolean isEqual(String src, String dest) {
                return src.replaceAll("\\s", "").equals(dest.replaceAll("\\s", ""));
            }

For example

Before change:

```
/**
** @testClasses TestSendInvoice
*/
global class sendInvoice {

	Webservice static String send(String invId){

		Invoice__c inv = [SELECT Id,Language__c,Contact_Invoice__c,Type__c,Ref_Invoice__c 
							FROM Invoice__c 
							WHERE id = :invId];
		if(InvoiceUtils.sendInvoice(inv)){
			return 'OK';
		}else{
			return 'ERROR';
		}

		return 'ERROR          ';
        }
}
```

After change:

```
/**
** @testClasses TestSendInvoice
*/
global class sendInvoice {

	Webservice static String send(String invId){

		Invoice__c inv = [SELECT Id,Language__c,Contact_Invoice__c,Type__c,Ref_Invoice__c 
							FROM Invoice__c 
							WHERE id = :invId];
		if(InvoiceUtils.sendInvoice(inv)){
			return 'OK';
		}else{
			return 'ERROR';
		}

		return 'ERROR';
        }
}
```

The difference in the last return is not catched by `delta-push` then the class will be not deployed

**Comment by LopezRegaladoFj** [comment]
I am testing with this regular expression `replaceAll("\\s*$", "")` instead of `replaceAll("\\s", "")` in order to replace special characters only at the end of the file and discard other characters inside the file @sfloess

**Comment by sfloess** [comment]
@LopezRegaladoFj - sorry just noticed this!  I didn't receive an email - or I'd have responded sooner :)

Nice catch btw!  Do you have a patch???

**Comment by LopezRegaladoFj** [comment]
Hi! I am using the method with this little change:

`            boolean isEqual(String src, String dest) {
                return src.replaceAll("\\s*$", "").equals(dest.replaceAll("\\s*$", ""));
            `

It seems to be ok, with this modification we are checking and replacing only at the end of the file

**Comment by sfloess** [comment]
@LopezRegaladoFj - let me give this some thought.  I'm not sure we want to modify solely for the end of the file.  I didn't consider a string constant change as you describe above.  One concern I have is if the file only changes from tabs to spaces (as an example).  I think we really want to remove all whitespace with the exception of anything contained within string constants.

**Comment by LopezRegaladoFj** [comment]
For example without this change we can not reformat our code, because Solenopsis can not detect changes in tabs/spaces @sfloess

**Comment by sfloess** [comment]
@LopezRegaladoFj - but should a non-code change that results in tabs vs spaces truly represent a code change?  If that's all that changed does it require a repush?

**Comment by LopezRegaladoFj** [comment]
agree, right now I am not sure what to do ;)

**Comment by pcon** [comment]
I have to agree with @LopezRegaladoFj it's been a problem for us in the past and I've just ignored it or did a direct push. I would say that whitespace only changes should be considered a diff.

**Comment by sfloess** [comment]
@LopezRegaladoFj / @pcon - two against one eh ;)  Ha ha!  No - that's fine.  I unilaterally decided whitespace wasn't right.  I'm definitely fine with changing this :)  I was more interested in talking through it to come up with a good plan.  I didn't realize this was a problem at all - so y'all win!  I'll definitely work the change :)

**Comment by sfloess** [comment]
@LopezRegaladoFj - put out a fix...give the latest version of Solenopsis a try (should be building shortly).

**Comment by sfloess** [comment]
@LopezRegaladoFj - I think I went a little too aggressive and definitely see your pt with the above reg ex.  I will get out a fix shortly.

Thank you for your persistence!  You are definitely a big help to the project :)

**Comment by sfloess** [comment]
@LopezRegaladoFj - I'm getting false positives with the regex...I'm debugging now...

**Comment by sfloess** [comment]
@LopezRegaladoFj - give that a try...i just pushed out the changes.
