### ISSUE TITLE
Create a file-delete command

### ISSUE THREAD

**Issue by pcon** [solenopsis/Solenopsis#248]
It would be nice to have a `file-delete` option.  Similar to `file-push` it would take parameters and add them to the `destructiveChanges.xml` file.  Currently you have to do a full `delta-push` or `destructive-push` to remove files.

**Comment by sfloess** [comment]
@pcon - nice idea man!  Challenge accepted!

**Comment by sfloess** [comment]
@pcon - I'm curious, how is this different than ```file-destructive-push```?

**Comment by pcon** [comment]
It's probably the same. Just need to support it wrapper

**Comment by sfloess** [comment]
@pcon - I'm gonna assign this to you then :)
