### ISSUE TITLE
Username and password as parameter in the conmmand line

### ISSUE THREAD

**Issue by LopezRegaladoFj** [solenopsis/Solenopsis#249]
It would be great if the username and password can be set in the command line as parameter instead of the credentials file, in this way we dont need to set the values in the file and the process is more agil and safe. What do you think? Thanks!

**Comment by pcon** [comment]
I think this is a fine idea.

**Comment by sfloess** [comment]
+1 - definitely see the value in having this functionality.  I'll try to get started on this sooner than later.

**Comment by sfloess** [comment]
@pcon - honoring the following via the `-D` command line option:
- `solenopsis.USER`
- `solenopsis.PASSWORD`
- `solenopsis.TOKEN`

I'll open an issue to support this via python...

**Comment by sfloess** [comment]
@pcon - opened #250 and assigned to you...

**Comment by sfloess** [comment]
@LopezRegaladoFj - still need to define a `solenopsis.DEPENDENT` property and file - but it does not have to contain credentials.  Long story but there'd be a bigger change for me to ignore that file's presence.

**Comment by LopezRegaladoFj** [comment]
@sfloess right! As a workaround I am going to create only two files in credentials folder; one for sandbox (developer, stage, etc) with the url 'test.salesforce.com' and another one for production with the url 'login.salesforce.com'. In this way we need only two files without modifications and the user can set the data values (user,password and token) as paramenters. Thanks!!!

**Comment by sfloess** [comment]
@LopezRegaladoFj - most welcome.  Bugs me about "needing" the credentials file with this new change.  There were some assumptions I made early on about only using the credentials file.  Without one, there is a reg-ex exception that happens in one (if not more) places.  I figured its not too bad to have to require a credentials file with minimal settings in it ;)

**Comment by LopezRegaladoFj** [comment]
@sfloess Really is enough with two credentials files; one for sandbox and another one for production with only the url inside them, I was testing and it is working fine! Thanks

**Comment by sfloess** [comment]
@LopezRegaladoFj - any time and most welcome!
