### ISSUE TITLE
A way to modify pollWaitMillis and maxPoll in Solenopsis?

### ISSUE THREAD

**Issue by adambarreiro** [solenopsis/Solenopsis#251]
Hi there,

First of all I wanted to thank you guys for developing this tool, it's helping us a lot!
So, we're currently deploying a lot of files, and we're getting this error:

`D:\solenopsis\ant\1.1\util\sfdc-util.xml:2661: Failed to obtain result from server within specified time of 3000sec.`

As you know with normal _ant-salesforce_ Ant tasks there are two attributes:
```
maxPoll
pollWaitMillis
```

Is there a way to change these values for Solenopsis? _solenopsis.properties_?

Thanks and regards.

**Comment by pcon** [comment]
If you are using the `solenopsis` command, you can add the `--maxpoll 60000` to increase the polling time.  If you're using `bsolenopsis` you'll have to add `-Dsf.maxPoll=60000`

If these don't work or I didn't answer your question correctly, feel free to re-open.

**Comment by adambarreiro** [comment]
Thanks @pcon! I'll check it out.
