### ISSUE TITLE
Solenopsis and Fedora 26 don't play well together

### ISSUE THREAD

**Issue by dvf1976** [solenopsis/Solenopsis#252]
It looks like Fedora 26 does not include python-argparse:

`
> [root@frink ~]# yum download solenopsis
> Failed to synchronize cache for repo 'Dropbox', disabling.
> Last metadata expiration check: 2:13:10 ago on Thu 13 Jul 2017 11:09:32 AM EDT.
> solenopsis-1.2-104.noarch.rpm                   6.0 MB/s |  16 MB     00:02    
> [root@frink ~]# rpm -ivh solenopsis-1.2-104.noarch.rpm 
> error: Failed dependencies:
> 	python-argparse is needed by solenopsis-1.2-104.noarch
`

AFAICS, it still seems to work ('solenopsis create test testClass' and 'solenopsis destructive-push' both appear to work) without after doing a '--force' install, however.

**Comment by sfloess** [comment]
@dvf1976 - I'm downloading the F26 ISO right now...  Let me see what I can figure out buddy :)

**Comment by sfloess** [comment]
@dvf1976 - I can reproduce btw...  Working on it...

**Comment by pcon** [comment]
I was looking and the newest versions of rpm let you say stuff like

```
Requires: (python >= 2.7.13 or (python < 2.7.13 and python-argparse))
```

Don't know if packages built with the new RPM spec will install on older versions. The RPM on rhel 7 isn't new enough to support this.

**Comment by sfloess** [comment]
@pcon - is there a way to encapsulate the above based upon OS?

**Comment by sfloess** [comment]
@pcon - btw @ openshift:
```
> rpmbuild --version
RPM version 4.8.0
```

**Comment by pcon** [comment]
4.12.0 is where they introduced this. The way that must repos handle this is to have a repo per version. IE a Fedora 26/rhel 7 specific repo

**Comment by sfloess** [comment]
@pcon - ah gotcha!  I'll have to update the build/publishing scripts to deal with this...

**Comment by sfloess** [comment]
@pcon - so a few things:
- The notation ```Requires: (python >= 2.7.13 or (python < 2.7.13 and python-argparse))``` does not work under RHEL 7.3.  ```rpmbuild``` fails and complains with:  ``` Dependency tokens must begin with alpha-numeric, '_' or '/': Requires: (python >= 2.7.13 or (python < 2.7.13 and python-argparse))```
- I was able to build the rpm under F26 just fine.  Install failed on ```python-argparse``` - so I will need to figure out the magic with this notation.

Regardless, we are in an interesting situation as we need F26 to build with this new notation.  I wonder if it wouldn't be simpler to do something like this in the ```solenopsis.spec```:

```
%install
...
yum install python-setuptools
easy_install argparse
```

Thoughts?

**Comment by sfloess** [comment]
@pcon - this worked for me on RHEL 7.3 as well...

**Comment by pcon** [comment]
Not sure if `easy_install` or `pip` is the "right"way to do this. I'm fine with dependency management this way.

**Comment by sfloess** [comment]
@pcon - yep agreed on the "not sure" part.  It does work for now, so I'm gonna go with the solution and close this issue.  Happy to revert and/or reopen if we need to do so.

**Comment by sfloess** [comment]
@dvf1976 - this should work for you now sir...
