### ISSUE TITLE
Getting an error in rh-util regex due to file separator

### ISSUE THREAD

**Issue by adambarreiro** [solenopsis/Solenopsis#253]
Hi,

I'm doing some trials with Solenopsis in a Jenkins instance, and when trying a _destructive-push_ I'm getting the following error, after the [report-diff]:

`BUILD FAILED
D:\solenopsis\ant\1.1\util\rh-util.xml:559: java.util.regex.PatternSyntaxException: Unclosed character class near index 7
^[\](.*)`

```
<!-- 
Remove the leading file separator (if it is there).  If it is not there,
simply use the value as is.
-->
<ac:propertyregex
property="@{property}"
override="true"
input="${rh-util.branch.BRANCH}"
regexp="^[${file.separator}](.*)" 
replace="\1"
defaultValue="${rh-util.branch.BRANCH}"
description="Remove the leading file separator if its there"/>
```
It seems `file.separator` evaluate to that `\`(I'm running Solenopsis in a Windows slave...) so it screws the regex... Is there a way to fix this? Do I have to switch to a Linux slave?

**Comment by pcon** [comment]
@adambarreiro can you please provide the content of your `solenopsis.properties` file, the credential file (with username/password/token obfuscated) and the full solenopsis/bsolenopsis command you are running?

**Comment by adambarreiro** [comment]
Sure @pcon,
**solenopsis.properties**
```
solenopsis.ENVIRONMENTS=dev uat pro local
solenopsis.env.HOME=D:\\solenopsis\\workspace
solenopsis.env.MASTER=local
solenopsis.env.DEPENDENT=dev
solenopsis.env.local.HOME=D:\\solenopsis\\workspace\\dev

sf.version = 33.0
```

**credentials**
```
username=*****@****.com
password=******
token=******
url=https://test.salesforce.com
```
**Command:**
```
ant -Dsf.env=dev -Dfast=true -Dsf.maxPoll=99999 -Dsf.pollWaitMillis=999999 -Dsf.purgeIgnores=true -f D:\\solenopsis\\ant\\solenopsis.xml destructive-push
```

**Comment by pcon** [comment]
So this is most likely because you're running this on Windows.  I'm going to kick this over to @sfloess since it's most likely how we parse paths in ant.  We've designed this primarily with *nix systems in mind so it may take some non-minor rejiggering to fix.

**Comment by adambarreiro** [comment]
@pcon Yeah, I suspected it from docs using Unix paths... But no problem, I can switch to a Linux node :)
Thanks!

**Comment by sfloess** [comment]
@adambarreiro - unfortunately I coded this with *nix in mind.  I've considered trying to fix this...but seeing how things are divided up between Ant and Beanshell, I just don't have the time to ensure I get everything worked out.  I'd prefer to wait on some rewriting efforts I'll be doing at some time and make Windows a consideration.  No ETA on when any of that may happen :(

Are you OK, for now, using a Linux node?  If so...mind if we close this issue?

**Comment by adambarreiro** [comment]
@sfloess Yeah, no problem! Thank you for the support

**Comment by sfloess** [comment]
@adambarreiro - most welcome!  I really appreciate your using solenopsis and bringing things to our attention - just makes this a better application :)
