### ISSUE TITLE
Maximum size of SOAP request reached. Batch size?

### ISSUE THREAD

**Issue by adambarreiro** [solenopsis/Solenopsis#254]
Hi,

We're triggering **delta-pushes** from a Jenkins instance and we're getting the following error:
```
/tmp/solenopsis/ant/1.1/util/sfdc-util.xml:2706: Failed to submit request to https://*******.salesforce.com/services/Soap/m/40.0/00D9E0000000h1Q for user *****@***.com.
Error: {http://schemas.xmlsoap.org/soap/envelope/}Client - Maximum size of request reached. Maximum size of request is 52428800 bytes.
```
I found that decreasing batch size makes smaller SOAP requests (or at least I understood that from what I read...). I put the flag `-Dsf.batchSize=20` (I read that by default Solenopsis has 300) and I'm getting the same error.

Any suggestions?

PS: If there's a better place for asking questions, please let me know! :)

**Comment by adambarreiro** [comment]
Hi...

I found reading my Jenkinsfile that I was putting the code into wrong folder... So when doing delta-push it was trying to upload _everything_.
I'm closing this question!

Regards.

**Comment by pcon** [comment]
@adambarreiro glad you figured it out.  I was waiting for @sfloess to come back from PTO but looks like he doesn't need to jump in.

Thanks for using the project.
