### ISSUE TITLE
Since Openshift v1 is being retired, we need to look at moving off of self-hosted Jenkins and onto something else

### ISSUE THREAD

**Issue by pcon** [solenopsis/Solenopsis#256]
I think the best solution is to move to [TravisCI]() using [copr]() to host the RPMs.  There is already [an example guide](https://gist.github.com/abn/daf262e7e454509df1429c87068923d1) for how to do this available.

**Comment by sfloess** [comment]
@pcon - I hadn't really dug into copr, but I'm curious if this is solely for building RPMs or is it more full featured?  For example can I still build and publish maven artifacts to bintray?  Mostly asking as I need to consider some of my other projects as well as solenopsis :)

**Comment by pcon** [comment]
No, it's just for RPMs

**Comment by sfloess** [comment]
@pcon - hey it's Thanksgiving!  Don't respond to this old guy's questions!

Anyway - thanks man...

**Comment by sfloess** [comment]
@pcon - I backed up all our jobs and .m2/settings.xml to a bitbucket private repo.  I sent you an invite.  I followed directions [here](https://www.sghill.net/how-do-i-backup-jenkins-jobs.html).  Was a little manual, but it worked for a backup :)

**Comment by sfloess** [comment]
@pcon - jobs have been copied over to our new [jenkins](https://jenkins-chromaiodes.rhcloud.com/)

**Comment by sfloess** [comment]
@pcon - I'm gonna close this...  My raspberry-pi is doing the needful for now...
