### ISSUE TITLE
Have a way to explicitly list entities to be added to the package.xml

### ISSUE THREAD

**Issue by pcon** [solenopsis/Solenopsis#257]
Most of the `package.xml` is generated on the fly and does not reference the `package.xml` that is stored on disk after doing a pull.  However, if you want to pull things (such as objects or layouts) from a managed package, you have to explicitly list them in the `package.xml`  It would be nice to have a file that lists the explicit items to be added to the `package.xml` 

## JSON Example
_package_extension.json_
```json
{
    "layouts": [
        "rh_escal__Escalation__c-Escalation Layout",
        "rh_escal__Escalation__c-Record Type Name Layout"
    ],
    "objects": [
        "rh_escal__Escalation__c"
    ]
}
```

## XML Example
_package_extension.xml_
```xml
<?xml version="1.0" encoding="UTF-8"?>
<PackageExtension>
    <types>
        <name>Layout</name>
        <members>rh_escal__Escalation__c-Escalation Layout</members>
        <members>rh_escal__Escalation__c-Record Type Name Layout</members>
    </types>
    <types>
        <name>CustomObject</name>
        <members>rh_escal__Escalation__c</members>
    </types>
</PackageExtension>
```

This would generate a `package.xml` that looks like
```xml
<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <!-- Standard package.xml stuff -->
    <types>
        <name>Layout</name>
        <members>*</members>
        <members>rh_escal__Escalation__c-Escalation Layout</members>
        <members>rh_escal__Escalation__c-Record Type Name Layout</members>
    </types>
    <types>
        <name>CustomObject</name>
        <members>*</members>
        <!-- List of standard objects -->
        <members>rh_escal__Escalation__c</members>
    </types>
    <!-- More package.xml stuff -->
</Package>
```

I think I like the JSON representation better, but I'm not 100% sold.  Also, I'm not sure if it should be `objects` like the directory is named or `CustomObject` like the `package.xml` shows

**Comment by sfloess** [comment]
@pcon - I think the simplest way to deal with this is XML (while I agree these days I prefer JSON).  Ant has built in tasks for XML and I can turn the XML into properties very easily.  Doing JSON will require me to add some libraries to the lib dir (it's doable and if you really prefer that, I can do it - just rather get it done for now) ;)

**Comment by pcon** [comment]
Ship it!

**Comment by sfloess** [comment]
@pcon - now you're talkin!

**Comment by sfloess** [comment]
@pcon - we already support the user supplying their own package.xml - I'll just make this an "sf.includePackageFile"

**Comment by sfloess** [comment]
@pcon - just an aside based upon your expected results above.  Forcing the elements together (merged) isn't necessary - you can have repeated ```<types>/<name>``` sub-elements...

**Comment by sfloess** [comment]
@pcon - mind giving the branch ```sfloess_issue-257``` a try?  Simply use the system property ```-Dsf.includePackageFile=[fully qualified path to a supplemental package]/[file].xml```.

Once you ack, I'll merge into master and document the new property...  Obviously we'll need some python command line magic to support this as well ;)

**Comment by sfloess** [comment]
@pcon - any chance in testing this?

**Comment by pcon** [comment]
@sfloess this week was a but of a cluster.  I did not get around to it.  I'll try my best to do it on Monday.

**Comment by sfloess** [comment]
@pcon - no worries and no rush!  Just checking in...and if done would cut a new release :)

**Comment by sfloess** [comment]
@pcon - I closed this as I believe its fixed...  We can reopen if not...

**Comment by sfloess** [comment]
Processing for ```<package>``` vs ```<Package>```.

Change the code to either honor both or just use ```<Package>```.
