### ISSUE TITLE
generate-full-package command does not include full custom object metadata

### ISSUE THREAD

**Issue by eddywebs** [solenopsis/Solenopsis#260]
Hi all ! this project seems very promising, I am wondering if generate-full-package command is working as desired ?
You see I am trying to generate package.xml manifest file based on metadata in the src/ dir present in the filesystem, however`solenopsis generate-package-xml ` generates a package.xml file which does not include any of our custom object metadata in src/objects/dir

**Comment by sfloess** [comment]
@eddywebs - may we close this issue or are there still questions?

**Comment by eddywebs** [comment]
Good to close thanks for the informaiton.
