### ISSUE TITLE
Deploy fail

### ISSUE THREAD

**Issue by nicolas1bruno** [solenopsis/Solenopsis#268]
`BUILD FAILED
/solenopsis/ant/1.1/solenopsis-build.xml:228: The following error occurred while executing this line:
/solenopsis/ant/1.1/util/sfdc-util.xml:3534: The following error occurred while executing this line:
/solenopsis/ant/1.1/util/sfdc-util.xml:3167: The following error occurred while executing this line:
/solenopsis/ant/1.1/util/sfdc-util.xml:3172: The following error occurred while executing this line:
/solenopsis/ant/1.1/util/sfdc-util.xml:3176: The following error occurred while executing this line:
/solenopsis/ant/1.1/util/sfdc-util.xml:3181: Failed to process the request successfully. Cause(UNKNOWN_EXCEPTION): Need to specify full name, Current Name: *, Required Delimiter: .
`

![image](https://user-images.githubusercontent.com/29508900/74744793-9555c700-5241-11ea-9b85-bcc272d30d6d.png)

version 48

This metadata listed above does not exist since version 33.0

Related with the last code changes, in version 1.2-125 of Solenopsis works fine

**Comment by pcon** [comment]
I noticed this today with `48.0` as well.  I'm working on updating Solenopsis to remove these for that API version.

**Comment by pcon** [comment]
Looks like when we were fixing #267 we accidentally included the metadata for the now deprecated and unsupported sharing rules.  I'm working on rolling back part of the commit for that so that this will work.

**Comment by pcon** [comment]
I've fixed part of this issue with ec1909d5d008925cbfc238f7e9b3c8be7c022fb0 but that just gets rid of the entity type errors.  I've narrowed down this issue to being something in the `destructiveChanges.xml` that's causing this error.

**Comment by sfloess** [comment]
@pcon - fixed...

Issue is Beanshell itself is able to grab attributes from Ant.  However, Ant lowercases the names internally.   Take a peek @ my recent commit to your pcon_268 branch.
