### ISSUE TITLE
Pull metadata for Einstein Bot queuing

### ISSUE THREAD

**Issue by preeti-preeti** [solenopsis/Solenopsis#278]
For Einstein Bot queuing we need metadata to be pulled for below configurations :
- Omni-Channel configuration under Chat Buttons and Invitation -- Puling some additional information like 'Omni Channel' option for routing type and queue information
- Routing Configurations
- Presence Configurations
- Presence Statuses

**Comment by pcon** [comment]
Fixed now in 1.3-7

0bb9e7ab428907ac1429261cdd82df99dfe2e510
